# Between Sessions — SAM Configuration File
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html
version = 0.1

[default.global.parameters]
stack_name = "between-sessions-production"
region = "ap-south-1"

[default.build.parameters]
cached = true
parallel = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
stack_name = "between-sessions-production"
region = "ap-south-1"

[default.package.parameters]
resolve_s3 = true

[default.sync.parameters]
watch = true

[default.local_start_api.parameters]
warm_containers = "LAZY"
skip_pull_image = true
port = 3000
host = "0.0.0.0"

[default.local_start_lambda.parameters]
warm_containers = "LAZY"
skip_pull_image = true
